name: EasyQuit Development Build

on:
  workflow_dispatch:
    inputs:
      release-new-build:
        type: boolean
        default: false
        description: 'Release new dev build'
        required: true

jobs:
  pre-release:
    name: Development Build
    runs-on: macos-26
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧪 Set Version and Build number
        run: |
          # CHANGE EVERY RELEASE:
          APP_VERSION="🧪 1.0.0"
          APP_BUILD=$(git rev-list --count HEAD)
          FROM_TAG=$(git describe --tags --abbrev=0 --exclude='prerelease')

          # Set VERSION
          latest_tag=$APP_VERSION
          echo "Latest tag: $latest_tag"
          sed -i -e "/VERSION =/ s/= .*/= $latest_tag/" EasyQuit/Config.xcconfig

          # Set BUILD_NUMBER
          latest_commit_number=$APP_BUILD
          echo "Latest commit number: $latest_commit_number"
          sed -i -e "/BUILD_NUMBER =/ s/= .*/= $latest_commit_number/" EasyQuit/Config.xcconfig

          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "APP_BUILD=$APP_BUILD" >> $GITHUB_ENV
          echo "FROM_TAG=$FROM_TAG" >> $GITHUB_ENV

      - name: 🔧 Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app"

      - name: 🎟️ Install Development & Developer ID Certificate
        env:
          DEVELOPMENT_CERT_BASE64: ${{ secrets.DEVELOPMENT_CERT_BASE64 }}
          DEVELOPER_ID_CERT_BASE64: ${{ secrets.DEVELOPER_ID_CERT_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          DEVELOPMENT_CERT_PATH=$RUNNER_TEMP/dev.p12
          DEVELOPER_ID_CERT_PATH=$RUNNER_TEMP/devid.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$DEVELOPMENT_CERT_BASE64" | base64 --decode -o $DEVELOPMENT_CERT_PATH
          echo -n "$DEVELOPER_ID_CERT_BASE64" | base64 --decode -o $DEVELOPER_ID_CERT_PATH

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $DEVELOPMENT_CERT_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $DEVELOPER_ID_CERT_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH

          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: 🎟️ Install Provision Profile
        if: false
        env:
          PROVISION_PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE_BASE64 }}
        run: |
          PP_PATH=$RUNNER_TEMP/EasyQuit.provisionprofile
          echo -n "$PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          
      - name: 🛠️ Build EasyQuit
        run: |
          xcodebuild \
            archive \
            -project EasyQuit.xcodeproj/ \
            -scheme "EasyQuit (GH ACTIONS)" \
            -destination 'generic/platform=macOS' \
            -archivePath dist/EasyQuit.xcarchive \
            -allowProvisioningUpdates

      - name: 🥡 Export EasyQuit.app
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath dist/EasyQuit.xcarchive \
            -exportPath dist/ \
            -exportOptionsPlist assets/ExportOptions.plist \
            -allowProvisioningUpdates

      - name: 🤏 Compress EasyQuit for notarization
        run: |
          ditto -c -k --sequesterRsrc --keepParent "dist/EasyQuit.app" "dist/EasyQuit.zip"
      
      - name: ✅ Notarize EasyQuit
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PWD: ${{ secrets.APPLE_ID_PWD }}
        run: |
          xcrun notarytool store-credentials EasyQuit --apple-id "$APPLE_ID" --team-id "$APPLE_TEAM_ID" --password "$APPLE_ID_PWD"
          xcrun notarytool submit "dist/EasyQuit.zip" --keychain-profile "EasyQuit" --wait
          xcrun stapler staple "dist/EasyQuit.app"

      - name: 🤏 Compress notarized EasyQuit
        run: |
          rm dist/EasyQuit.zip
          ditto -c -k --sequesterRsrc --keepParent "dist/EasyQuit.app" "dist/EasyQuit.zip"

      - name: ⬆️ Upload EasyQuit
        uses: actions/upload-artifact@v4
        with:
          name: EasyQuit
          path: dist/EasyQuit.zip

      - name: 🏷️ Create/update tag
        uses: actions/github-script@v7
        if: "${{ inputs.release-new-build }}"
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/prerelease',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/prerelease',
                sha: context.sha
              });
            })

      - name: 📰 Build Changelog
        uses: mikepenz/release-changelog-builder-action@v4
        if: "${{ inputs.release-new-build }}"
        with:
          outputFile: CHANGELOG.md
          fromTag: ${{ env.FROM_TAG }}
          toTag: "prerelease"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n## 💭 Uncategorized\n#{{UNCATEGORIZED}}",
              "pr_template": "- #{{TITLE}} ##{{NUMBER}}",
              "categories": [
                {
                    "title": "## ✨ New Features",
                    "labels": ["Feature", "Luminare", "Improvement"]
                },
                {
                    "title": "## 🐞 Bug Fixes",
                    "labels": ["Bug"]
                },
                {
                    "title": "## 🌐 Localization",
                    "labels": ["Localization"]
                }
              ],
              "empty_template": "- ❌ No changes found"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🥳 Publish Dev Build
        uses: ncipollo/release-action@v1
        if: "${{ inputs.release-new-build }}"
        with:
          allowUpdates: true
          artifacts: dist/EasyQuit.zip
          commit: develop
          bodyFile: CHANGELOG.md
          name: "Development Build: ${{ env.APP_VERSION }} (${{ env.APP_BUILD }})"
          prerelease: true
          tag: "prerelease"

      - name: 🧹 Cleanup
        run: |
          security delete-keychain "$RUNNER_TEMP/app-signing.keychain-db"